# Generated by Django 5.1.3 on 2024-12-06 01:47

from decimal import Decimal
from django.db import migrations, models

def clear_bracket_costs(apps, schema_editor):
    BracketCosts = apps.get_model('solar', 'BracketCosts')
    BracketCosts.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ("solar", "0009_bill_document_alter_potentialcustomers_id_quote"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bracketcosts",
            options={
                "verbose_name": "Bracket Cost",
                "verbose_name_plural": "Bracket Costs",
            },
        ),
        # First remove old fields
        migrations.RemoveField(
            model_name="bracketcosts",
            name="SystemRange",
        ),
        migrations.RemoveField(
            model_name="bracketcosts",
            name="Type",
        ),
        migrations.RemoveField(
            model_name="bracketcosts",
            name="cost",
        ),
        # Clear existing data
        migrations.RunPython(clear_bracket_costs),
        # Then add new fields
        migrations.AddField(
            model_name="bracketcosts",
            name="min_size",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Minimum system size in kW",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="bracketcosts",
            name="max_size",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("999.00"),
                help_text="Maximum system size in kW",
                max_digits=5,
            ),
        ),
        # Add remaining fields
        migrations.AddField(
            model_name="bracketcosts",
            name="ac_cable",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10000.00"),
                help_text="AC cable cost for this bracket",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="bracketcosts",
            name="accessories",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("20000.00"),
                help_text="Accessories cost for this bracket",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="bracketcosts",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="bracketcosts",
            name="dc_cable",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("15000.00"),
                help_text="DC cable cost for this bracket",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="bracketcosts",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        # Finally set the unique constraint
        migrations.AlterUniqueTogether(
            name="bracketcosts",
            unique_together={("min_size", "max_size")},
        ),
    ]
