# Generated by Django 5.1.3 on 2025-03-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0010_alter_bracketcosts_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l2', models.BooleanField(default=False)),
            ],
        ),
    ]
