# Generated by Django 5.1.3 on 2025-03-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0011_structuretype'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuretype',
            name='abs_cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structuretype',
            name='custom_cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
